export const enum EnvEnum{
	JWT_ACCESS_SECRET="JWT_ACCESS_SECRET",
	JWT_REFRESH_SECRET="JWT_REFRESH_SECRET",
	EMAIL_PASS="EMAIL_PASS",
	EMAIL_LOGIN="EMAIL_LOGIN",
	RMQ_EXCHANGE="RMQ_EXCHANGE",
	RMQ_PASSWORD="RMQ_PASSWORD",
	RMQ_LOGIN="RMQ_LOGIN",
	RMQ_HOST="RMQ_HOST"
}